name: p7zip-desktop
adopt-info: p7zip-desktop
summary: 7Zip Desktop
grade: stable
description: |
  7-Zip is a file archiver with a high compression ratio, this package also includes the graphic frontend for maximum cosiness on the desktop

confinement: strict
license: GPL-2.1
compression: lzo

assumes:
  - command-chain
  
apps:
  p7zip-desktop:
    command: desktop-launch $SNAP/usr/local/bin/7zDesktop
    command-chain: 
      - bin/homeishome-launch       
#    desktop: usr/share/applications/7zFM.desktop
    plugs:
      - x11
      - wayland 
      - desktop
      - desktop-legacy
      - home
      - removable-media
    
environment:
  GTK_PATH: $SNAP/lib/gtk-2.0
  GTK_DATA_PREFIX: $SNAP
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
  QT_QPA_PLATFORMTHEME: gtk2
  
plugs:
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes   
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes:gtk-2-engines
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk2-common-themes:gtk-2-themes

parts:
  desktop-gtk2:
  wxwidgets-3-0-gtk2:
  
  p7zip-desktop:
    plugin: dump 
    source: .
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    override-build: |
      rm -rf "$SNAPCRAFT_PART_INSTALL/*"
      make 7zFM 7zG
      make install DEST_DIR="$SNAPCRAFT_PART_INSTALL"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/usr/share/applications"
      cp 7zFM.desktop "$SNAPCRAFT_PART_INSTALL/usr/share/applications/7zFM.desktop"
      cp 7zDesktop "$SNAPCRAFT_PART_INSTALL/usr/local/bin/7zDesktop"
      chmod +x "$SNAPCRAFT_PART_INSTALL/usr/local/bin/7zDesktop"
      chmod +x "$SNAPCRAFT_PART_INSTALL/usr/local/bin/p7zipForFilemanager"
      install -dm755 "$SNAPCRAFT_PART_INSTALL/usr/local/lib/p7zip/help"
      cp -r DOC/MANUAL/* "$SNAPCRAFT_PART_INSTALL/usr/local/lib/p7zip/help"
      
    build-packages:
      - gcc
      - g++
      - make
      - libwxgtk3.0-dev
      - yasm
      - python
    stage-packages:
      - overlay-scrollbar
      - overlay-scrollbar-gtk2
      - libatk-adaptor
      - libgail-common
      - libcanberra-gtk-module
      - qt5-style-plugins
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch           
