name: p7zip-desktop
#adopt-info: p7zip-desktop
version: "git"
summary: 7Zip Desktop
grade: stable
description: |
  7-Zip is a file archiver with a high compression ratio, this package also includes the graphic frontend for maximum cosiness on the desktop

confinement: strict
license: GPL-2.1
compression: lzo
base: core20

assumes:
  - command-chain
  
apps:
  p7zip-desktop:
    extensions:
      - gnome-3-38  
    command: bin/7zDesktop
    command-chain: 
      - bin/homeishome-launch       
    plugs:
      - x11
      - wayland 
      - desktop
      - desktop-legacy
      - home
      - removable-media
    
parts:
  p7zip-desktop:
    source: https://github.com/kz6fittycent/p7zip
    source-type: git  
    plugin: make
    
#    override-pull: |
#      snapcraftctl pull
#      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
    build-packages:
      - gcc
      - g++
      - make
      - libwxgtk3.0-gtk3-dev
      - yasm
      - python
      
    stage-packages:
      - overlay-scrollbar
      - overlay-scrollbar-gtk2
      - libatk-adaptor
      - libgail-common
      - libcanberra-gtk-module
      - qt5-style-plugins
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch           
